export const GET_COURSES = "GET_COURSES"
export const GET_COURSE_BY_ID = "GET_COURSE_BY_ID"
export const LOADING_COURSE = "LOADING_COURSE"
export const ADD_COURSE = "ADD_COURSE"
export const DELETE_COURSE = "DELETE_COURSE"
export const EDIT_COURSE = "EDIT_COURSE"
export const ERROR = "ERROR"
